import = [
    "~/.config/alacritty/themes/themes/palenight.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new", "-A", "-s nexxai"]

[keyboard]
bindings = [
    { key = "t", mods = "Super", chars = "\u0002c" }, # Create new tab (tmux)
    { key = "w", mods = "Super", chars = "\u0002&" }, # Close current tab (tmux)
    { key = "Tab", mods = "Control", chars = "\u0002n" }, # Switch to next tab (tmux)
    { key = "Tab", mods = "Control|Shift", chars = "\u0002p" }, # Switch to previous tab (tmux)
    { key = "/", mods = "Super", chars = " aq" }, # Toggle comments in vim 
    { key = "k", mods = "Super", chars = "\u000c\u000b" } # Send Ctrl-L to clear the screen and Ctrl-K to tmux to clear its history
]

[window]
padding = { x = 13, y = 13 }
position = { x = 170, y = 203 }
dynamic_padding = true
dimensions = { lines = 25, columns = 165 }
decorations = "Buttonless"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Regular" }
italic = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 15
offset = { x = 0, y = 24 }
glyph_offset = { x = 0, y = 12 }

[colors]
cursor = { cursor = "#ffdd00" }
draw_bold_text_with_bright_colors = true

[colors.primary]
foreground = "#959dcb"
background = "#292d3e"
bright_foreground = "#edeeed"

[cursor]
thickness = 0.5
